# -*- coding: utf-8 -*-
"""AIES_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5oMP2SgaxU5Xg6ofg6QBP8MhUOp43iz
"""

def evaluate(board):
    for row in range(3):
        if board[row][0] == board[row][1] == board[row][2]:
            if board[row][0] == 'x':
                return 10
            elif board[row][0] == 'o':
                return -10
    for col in range(3):
        if board[0][col] == board[1][col] == board[2][col]:
            if board[0][col] == 'x':
                return 10
            elif board[0][col] == 'o':
                return -10
    # Check diagonals
    if board[0][0] == board[1][1] == board[2][2]:
        if board[0][0] == 'x':
            return 10
        elif board[0][0] == 'o':
            return -10
    if board[0][2] == board[1][1] == board[2][0]:
        if board[0][2] == 'x':
            return 10
        elif board[0][2] == 'o':
            return -10
    return 0  # No winner

def is_board_full(board):
    for row in board:
        for cell in row:
            if cell == '_':
                return False
    return True

def minimax(board, depth, is_max_player):
    score = evaluate(board)

    #Max wins
    if score == 10:
        return score - depth

    #min wins
    if score == -10:
        return score + depth

    #draw
    if is_board_full(board):
        return 0

    if is_max_player:
        best = -float('inf')

        for i in range(3):
            for j in range(3):
                if board[i][j] == '_':
                    board[i][j] = 'x'
                    best = max(best, minimax(board, depth + 1, False))
                    board[i][j] = '_'
        return best
    else:
        best = float('inf')

        for i in range(3):
            for j in range(3):
                if board[i][j] == '_':
                    board[i][j] = 'o'
                    best = min(best, minimax(board, depth + 1, True))
                    board[i][j] = '_'
        return best


def find_best_move(board):
    best_val = -float('inf')
    best_move = (-1, -1)


    for i in range(3):
        for j in range(3):
            if board[i][j] == '_':
                board[i][j] = 'x'
                move_val = minimax(board, 0, False)
                board[i][j] = '_'
                if move_val > best_val:
                    best_move = (i, j)
                    best_val = move_val
    return best_move

def print_board(board):
    for row in board:
        print(' '.join(row))
    print()

def main():
    board = [['_' for _ in range(3)] for _ in range(3)]

    while True:
        print_board(board)

        row, col = map(int, input("Enter row and column for 'o' (space separated): ").split())
        if board[row][col] == '_':
            board[row][col] = 'o'
        else:
            print("Invalid move. Try again.")
            continue


        if evaluate(board) == -10:
            print_board(board)
            print("Player 'o' wins!")
            break
        elif is_board_full(board):
            print_board(board)
            print("It's a draw!")
            break


        print("AI (Player 'x') is making its move...")
        move = find_best_move(board)
        board[move[0]][move[1]] = 'x'


        if evaluate(board) == 10:
            print_board(board)
            print("AI (Player 'x') wins!")
            break
        elif is_board_full(board):
            print_board(board)
            print("It's a draw!")
            break


if __name__ == "__main__":
    main()

