# -*- coding: utf-8 -*-
"""AIES_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaDszgwzBY6WUVt16qUVyuRaeGq9Lb8m
"""

class Variable:
    def __init__(self, value):
        self.value = value
    def __eq__(self, other):
        return isinstance(other, Variable) and self.value == other.value
    def __repr__(self):
        return f"Variable('{self.value}')"

class Constant:
    def __init__(self, value):
        self.value = value
    def __eq__(self, other):
        return isinstance(other, Constant) and self.value == other.value
    def __repr__(self):
        return f"Constant('{self.value}')"

class Rel:
    def __init__(self, name, args=None):
        self.name = name
        self.args = args if args else []
    def __repr__(self):
        return f"Rel('{self.name}', {self.args})"

def Unify(L1, L2, testset):
    # Checking if both are variables or constants
    if (isinstance(L1, Variable) or isinstance(L2, Variable) or
        isinstance(L1, Constant) or isinstance(L2, Constant)):

        if L1 == L2:
            return None
        elif isinstance(L1, Variable):
            if isinstance(L2, Variable):
                print("Both mismatching variables")
                return False
            else:
                if L1.value not in testset.values():
                    return [L2, L1]
                else:
                    print("Ambiguous Variable")
                    return False
        elif isinstance(L2, Variable):
            if isinstance(L1, Variable):
                print("Both mismatching variables")
                return False
            else:
                if L2.value not in testset.values():
                    return [L1, L2]
                else:
                    print("Ambiguous Variable")
                    return False
        else:
            print("Mismatch")
            return False

    # Ensuring the functions (relations) are the same
    elif L1.name != L2.name:
        print("Relation Mismatch")
        return False

    # Ensuring the functions have the same number of arguments
    elif len(L1.args) != len(L2.args):
        print("Length does not match")
        return False

    SUBSET = {}
    for i in range(len(L1.args)):
        S = Unify(L1.args[i], L2.args[i], SUBSET)
        if S == False:
            return False
        if S is not None:
            SUBSET[S[0].value] = S[1].value
    return SUBSET

if __name__ == "__main__":
    print(Unify(Rel("Knows"), Rel("Knows"), {}))
    print()

    print(Unify(
        Rel("Knows", [Variable("Y")]),
        Rel("Knows", [Variable("Y")]),
        {}
    ))
    print()

    print(Unify(
        Rel("Knows", [Constant("Raj"), Variable("X")]),
        Rel("Knows", [Variable("X"), Constant("Seeta")]),
        {}
    ))

